jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
server:
  port: 9000
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
---
spring:
  profiles:
    active: dev
---
spring:
  sql:
    init:
      mode: always
      data-locations: db/data-h2.sql
      schema-locations: db/schema-h2.sql
  datasource:
    url: jdbc:h2:mem:isocial
    username: admin
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: dev
---
---
spring:
  flyway:
    enabled: false
  sql:
    init:
      mode: never
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  config:
    activate:
      on-profile: prod
